export enum ConfigurationEnum {
    PORT = 'PORT',
    HOST = 'HOST',
    DATABASE_TYPE = 'postgres',
    DATABASE_PORT = 'POSTGRES_PORT',
    DATABASE_HOST = 'POSTGRES_HOST',
    DATABASE_USER = 'POSTGRES_USER',
    DATABASE_PASSWORD = 'POSTGRES_PASSWORD',
    DATABASE = 'POSTGRES_DB',
    JWT_SECRET = 'JWT_SECRET',
    ADM_SECRET = 'ADM_SECRET',
}